In [ ]:
!pip install pandas


In [ ]:
import numpy as np
import pandas as pd

In [ ]:
fcuk =[25,636,892,759,1552]

In [ ]:
np.array(fcuk)

array([  25,  636,  892,  759, 1552])

In [ ]:
pd.Series(fcuk)

0      25
1     636
2     892
3     759
4    1552
dtype: int64

In [ ]:
list1=("A","aditya","bhushan","rahul")

In [ ]:
np.array(list1)

array(['A', 'aditya', 'bhushan', 'rahul'], dtype='<U7')

In [ ]:
pd.Series(list1)

0          A
1     aditya
2    bhushan
3      rahul
dtype: object

In [ ]:
starc = {1:"rohit sharma",2:"virat kohli",3:"msd"}

In [ ]:
np.array(starc)

array({1: 'rohit sharma', 2: 'virat kohli', 3: 'msd'}, dtype=object)

In [ ]:
starc =

In [ ]:
data = {
    "Name":["rohit sharm","virat kohli","msd"],
    'Age':[25,63,98],
    "salary":[100000,5000,63265555]

}

In [ ]:
type(data)

dict

In [ ]:
df=pd.DataFrame(data)

In [ ]:
df

Name  Age    salary
0  rohit sharm   25    100000
1  virat kohli   63      5000
2          msd   98  63265555

In [ ]:
df =pd.read_csv("/content/sample_data/mnist_test.csv")

In [ ]:
df

7  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.658  0.659  0.660  \
0     2  0    0    0    0    0    0    0    0    0  ...      0      0      0   
1     1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
2     0  0    0    0    0    0    0    0    0    0  ...      0      0      0   
3     4  0    0    0    0    0    0    0    0    0  ...      0      0      0   
4     1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
...  .. ..  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...    ...   
9994  2  0    0    0    0    0    0    0    0    0  ...      0      0      0   
9995  3  0    0    0    0    0    0    0    0    0  ...      0      0      0   
9996  4  0    0    0    0    0    0    0    0    0  ...      0      0      0   
9997  5  0    0    0    0    0    0    0    0    0  ...      0      0      0   
9998  6  0    0    0    0    0    0    0    0    0  ...      0      0      0   

      0.661  0.662  0.663  0.664  0.665  0.666  0.667  
0         0      0      0      0      0      0      0  
1         0      0      0      0      0      0      0  
2         0      0      0      0      0      0      0  
3         0      0      0      0      0      0      0  
4         0      0      0      0      0      0      0  
...     ...    ...    ...    ...    ...    ...    ...  
9994      0      0      0      0      0      0      0  
9995      0      0      0      0      0      0      0  
9996      0      0      0      0      0      0      0  
9997      0      0      0      0      0      0      0  
9998      0      0      0      0      0      0      0  

[9999 rows x 785 columns]

In [30]:
df.index

RangeIndex(start=0, stop=9999, step=1)

In [33]:
df.columns

Index(['7', '0', '0.1', '0.2', '0.3', '0.4', '0.5', '0.6', '0.7', '0.8',
       ...
       '0.658', '0.659', '0.660', '0.661', '0.662', '0.663', '0.664', '0.665',
       '0.666', '0.667'],
      dtype='object', length=785)

In [36]:
df.dtypes

7        int64
0        int64
0.1      int64
0.2      int64
0.3      int64
         ...  
0.663    int64
0.664    int64
0.665    int64
0.666    int64
0.667    int64
Length: 785, dtype: object

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9999 entries, 0 to 9998
Columns: 785 entries, 7 to 0.667
dtypes: int64(785)
memory usage: 59.9 MB


In [40]:
df1 = pd.DataFrame({"age":[25,56],
                    "height":[25,878],
                    "weitghbt":[25851,562]


})

In [41]:
df1

age  height  weitghbt
0   25      25     25851
1   56     878       562

In [43]:
df1.values

array([[   25,    25, 25851],
       [   56,   878,   562]])

array([[   25,    25, 25851],
       [   56,   878,   562]])

In [44]:
df.axes

[RangeIndex(start=0, stop=9999, step=1),
 Index(['7', '0', '0.1', '0.2', '0.3', '0.4', '0.5', '0.6', '0.7', '0.8',
        ...
        '0.658', '0.659', '0.660', '0.661', '0.662', '0.663', '0.664', '0.665',
        '0.666', '0.667'],
       dtype='object', length=785)]

In [45]:
df1.index

RangeIndex(start=0, stop=2, step=1)

In [46]:
df.size

7849215

In [47]:
df.shape

(9999, 785)

In [48]:
df.head()

7  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.658  0.659  0.660  \
0  2  0    0    0    0    0    0    0    0    0  ...      0      0      0   
1  1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
2  0  0    0    0    0    0    0    0    0    0  ...      0      0      0   
3  4  0    0    0    0    0    0    0    0    0  ...      0      0      0   
4  1  0    0    0    0    0    0    0    0    0  ...      0      0      0   

   0.661  0.662  0.663  0.664  0.665  0.666  0.667  
0      0      0      0      0      0      0      0  
1      0      0      0      0      0      0      0  
2      0      0      0      0      0      0      0  
3      0      0      0      0      0      0      0  
4      0      0      0      0      0      0      0  

[5 rows x 785 columns]

In [49]:
df.head(2)

7  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.658  0.659  0.660  \
0  2  0    0    0    0    0    0    0    0    0  ...      0      0      0   
1  1  0    0    0    0    0    0    0    0    0  ...      0      0      0   

   0.661  0.662  0.663  0.664  0.665  0.666  0.667  
0      0      0      0      0      0      0      0  
1      0      0      0      0      0      0      0  

[2 rows x 785 columns]

In [50]:
df.tail()

7  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.658  0.659  0.660  \
9994  2  0    0    0    0    0    0    0    0    0  ...      0      0      0   
9995  3  0    0    0    0    0    0    0    0    0  ...      0      0      0   
9996  4  0    0    0    0    0    0    0    0    0  ...      0      0      0   
9997  5  0    0    0    0    0    0    0    0    0  ...      0      0      0   
9998  6  0    0    0    0    0    0    0    0    0  ...      0      0      0   

      0.661  0.662  0.663  0.664  0.665  0.666  0.667  
9994      0      0      0      0      0      0      0  
9995      0      0      0      0      0      0      0  
9996      0      0      0      0      0      0      0  
9997      0      0      0      0      0      0      0  
9998      0      0      0      0      0      0      0  

[5 rows x 785 columns]

In [51]:
df.tail(2)

7  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.658  0.659  0.660  \
9997  5  0    0    0    0    0    0    0    0    0  ...      0      0      0   
9998  6  0    0    0    0    0    0    0    0    0  ...      0      0      0   

      0.661  0.662  0.663  0.664  0.665  0.666  0.667  
9997      0      0      0      0      0      0      0  
9998      0      0      0      0      0      0      0  

[2 rows x 785 columns]

In [52]:
df.describe()

7       0     0.1     0.2     0.3     0.4     0.5     0.6  \
count  9999.000000  9999.0  9999.0  9999.0  9999.0  9999.0  9999.0  9999.0   
mean      4.443144     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
std       2.895897     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
min       0.000000     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
25%       2.000000     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
50%       4.000000     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
75%       7.000000     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
max       9.000000     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

          0.7     0.8  ...        0.658        0.659        0.660  \
count  9999.0  9999.0  ...  9999.000000  9999.000000  9999.000000   
mean      0.0     0.0  ...     0.179318     0.163616     0.052605   
std       0.0     0.0  ...     5.674433     5.736359     2.420125   
min       0.0     0.0  ...     0.000000     0.000000     0.000000   
25%       0.0     0.0  ...     0.000000     0.000000     0.000000   
50%       0.0     0.0  ...     0.000000     0.000000     0.000000   
75%       0.0     0.0  ...     0.000000     0.000000     0.000000   
max       0.0     0.0  ...   253.000000   253.000000   156.000000   

             0.661   0.662   0.663   0.664   0.665   0.666   0.667  
count  9999.000000  9999.0  9999.0  9999.0  9999.0  9999.0  9999.0  
mean      0.000600     0.0     0.0     0.0     0.0     0.0     0.0  
std       0.060003     0.0     0.0     0.0     0.0     0.0     0.0  
min       0.000000     0.0     0.0     0.0     0.0     0.0     0.0  
25%       0.000000     0.0     0.0     0.0     0.0     0.0     0.0  
50%       0.000000     0.0     0.0     0.0     0.0     0.0     0.0  
75%       0.000000     0.0     0.0     0.0     0.0     0.0     0.0  
max       6.000000     0.0     0.0     0.0     0.0     0.0     0.0  

[8 rows x 785 columns]