In [77]:
!pip install numpy

In [78]:
import numpy as np


In [79]:
arr=np.array([1,2,3,4,5,6,7,8])

In [80]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [81]:
arr1=np.array([[1,2,3],[4,5,6,]])

In [82]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [83]:
arr.ndim

1

In [84]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [85]:
arr1.ndim

2

In [86]:
arr.shape

(8,)

In [87]:
arr1.shape

(2, 3)

In [88]:
arr.size

8

In [89]:
arr1.size

6

In [90]:
arr.dtype

dtype('int64')

In [91]:
arr1.dtype

dtype('int64')

In [92]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [93]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [94]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [95]:
np.full((3,3),2)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [96]:
np.full((4,9),4)

array([[4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4]])

# indexing and slicing

In [97]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [98]:
arr[4]

5

In [99]:
arr[6]

7

In [100]:
arr[2:4]

array([3, 4])

In [101]:
arr1[5:6]

array([], shape=(0, 3), dtype=int64)

In [102]:
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [103]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [104]:
arr2[1,2]

6

In [105]:
arr2[0:2,3:5]

array([], shape=(2, 0), dtype=int64)

In [106]:
arr2.dtype

dtype('int64')

In [107]:
arr2.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [108]:
arr2.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [109]:
arr2.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [110]:
arr2.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [111]:
arr3=np.array([1,2,3,4,5,6,7,8,9])

In [112]:
arr.size

8

In [113]:
arr3.size

9

In [114]:
arr3.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [115]:
arr3.ndim

1

In [117]:
arr4=arr3.reshape(1,9)

In [118]:
arr4

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

#numpy2

In [119]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [121]:
np.arange(2,9,2)

array([2, 4, 6, 8])

In [123]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [124]:
arr=np.array([8,4,5,5,6,3,8,9])

In [127]:
arr=np.array([5,6,4,8,9,2,6,8])

In [128]:
np.sort(arr)

array([2, 4, 5, 6, 6, 8, 8, 9])

In [129]:
arr.max()

9

In [130]:
arr.sum()

48

In [131]:
np.unique(arr)

array([2, 4, 5, 6, 8, 9])

In [132]:
arr

array([5, 6, 4, 8, 9, 2, 6, 8])

In [133]:
np.mean(arr)

6.0

In [134]:
np.median(arr)

6.0

In [135]:
from scipy import stats

In [136]:
stats.mode(arr)

ModeResult(mode=6, count=2)

In [137]:
arr

array([5, 6, 4, 8, 9, 2, 6, 8])

In [138]:
np.var(arr)

4.75

In [139]:
np.std(arr)

2.179449471770337

In [141]:
np.corrcoef(arr)

1.0

In [143]:
np.percentile(arr,25)

4.75

In [144]:
np.percentile(arr,75)

8.0

In [145]:
np.percentile(arr,75)-np.percentile(arr,25)

3.25

In [151]:
x=np.array([1,2,3,4,5,6])
y=np.array([2,4,9,1,5,4,5])

In [157]:
np.corrcoef(x,y)

array([[1., 1.],
       [1., 1.]])

In [155]:
x = np.array([1,2,3,4,5])
y = np.array([2,4,6,8,10])

In [156]:
np.corrcoef(x,y)

array([[1., 1.],
       [1., 1.]])

In [158]:
np.cov(x,y)

array([[ 2.5,  5. ],
       [ 5. , 10. ]])

In [161]:
np.random.randint(1,100,5)

array([29, 70,  4, 30, 52])

In [162]:
np.random.rand(5)

array([0.12964612, 0.12046231, 0.85633324, 0.67168472, 0.06473062])

In [164]:
np.random.randn(5)

array([-1.09160469, -0.19691842,  2.34096551,  2.07363009,  0.57000901])